/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{vue,ts}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'on-tertiary-container': '#008cc7',
        'inverse-surface': '#2d3133',
        'on-primary': '#ffffff',
        'surface-dim': '#d8dadc',
        'secondary-fixed-dim': '#b9c7e0',
        'inverse-on-surface': '#eff1f3',
        'primary-fixed-dim': '#bec6e0',
        'on-surface-variant': '#45464d',
        'surface-variant': '#e0e3e5',
        'inverse-primary': '#bec6e0',
        'on-surface': '#191c1e',
        error: '#ba1a1a',
        'tertiary-fixed': '#c9e6ff',
        'on-background': '#191c1e',
        'on-primary-fixed': '#131b2e',
        'error-container': '#ffdad6',
        'surface-container': '#eceef0',
        'outline-variant': '#c6c6cd',
        'on-error-container': '#93000a',
        'on-tertiary-fixed': '#001e2f',
        'tertiary-container': '#001e2f',
        tertiary: '#000000',
        'on-tertiary-fixed-variant': '#004c6e',
        primary: '#000000',
        'on-primary-fixed-variant': '#3f465c',
        surface: '#f7f9fb',
        background: '#f7f9fb',
        'surface-tint': '#565e74',
        'secondary-container': '#d5e3fd',
        'surface-container-lowest': '#ffffff',
        'primary-container': '#131b2e',
        'on-secondary-fixed': '#0d1c2f',
        'secondary-fixed': '#d5e3fd',
        'surface-container-low': '#f2f4f6',
        'surface-bright': '#f7f9fb',
        secondary: '#515f74',
        'on-primary-container': '#7c839b',
        'on-secondary-fixed-variant': '#3a485c',
        'primary-fixed': '#dae2fd',
        'on-secondary': '#ffffff',
        'tertiary-fixed-dim': '#89ceff',
        'surface-container-high': '#e6e8ea',
        'surface-container-highest': '#e0e3e5',
        outline: '#76777d',
        'on-secondary-container': '#57657b',
        'on-error': '#ffffff',
        'on-tertiary': '#ffffff',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'container-margin': '2rem',
        xs: '0.25rem',
        base: '4px',
        lg: '1.5rem',
        gutter: '1.5rem',
        sm: '0.5rem',
        md: '1rem',
        xl: '2rem',
        '2xl': '3rem',
      },
      fontFamily: {
        'body-md': ['Inter'],
        'table-data': ['Inter'],
        'display-lg': ['Inter'],
        'headline-sm': ['Inter'],
        'headline-md': ['Inter'],
        'label-md': ['Inter'],
        'body-lg': ['Inter'],
        'body-sm': ['Inter'],
      },
      fontSize: {
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'table-data': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'display-lg': [
          '36px',
          { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' },
        ],
        'headline-sm': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'headline-md': [
          '24px',
          { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' },
        ],
        'label-md': ['13px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '18px', fontWeight: '400' }],
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
}
